// Tailwind config dedicated to compiling the mockup-render stylesheet that
// gets inlined into the sandbox iframe (see
// src/components/mockups/buildMockupSrcDoc.ts).
//
// The mockup HTML is generated by an LLM, so the utility classes used can't
// be enumerated statically. Instead of relying on the Tailwind Play CDN's
// in-browser JIT (which is slow, network-dependent, and the root cause of
// "Preview degraded: Tailwind styles did not apply" reports), we precompile
// a comprehensive utility sheet at build time by safelisting the full
// regularly-emitted utility surface area.
//
// Size budget: the generated file is inlined into every preview iframe so
// it must stay reasonable. Currently ~600 KB minified — large enough to
// cover most LLM-emitted utilities, small enough not to noticeably slow
// the preview. Avoid expanding variants × colors cartesians; cost grows
// fast.
//
// Run via: `npm run mockup-css:build` (writes src/styles/mockup-tailwind.generated.css).

const PALETTE = [
    'slate', 'gray', 'zinc', 'neutral', 'stone',
    'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal',
    'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
].join('|');
const SHADES = '50|100|200|300|400|500|600|700|800|900|950';
const SPACING = '0|0\\.5|1|1\\.5|2|2\\.5|3|3\\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96|px';
const FRACTIONS = '1\\/2|1\\/3|2\\/3|1\\/4|2\\/4|3\\/4|1\\/5|2\\/5|3\\/5|4\\/5|1\\/6|5\\/6|1\\/12|2\\/12|3\\/12|4\\/12|5\\/12|6\\/12|7\\/12|8\\/12|9\\/12|10\\/12|11\\/12';
const SIZE_KEYWORDS = 'auto|full|screen|min|max|fit|svh|lvh|dvh';
const MAX_W_NAMED = 'none|xs|sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|prose|screen-sm|screen-md|screen-lg|screen-xl|screen-2xl';
const RESPONSIVE = ['md', 'lg'];

const colorProperties = ['bg', 'text', 'border', 'ring', 'fill', 'stroke', 'from', 'to', 'via', 'placeholder', 'caret', 'accent', 'divide', 'decoration', 'outline'];

module.exports = {
    content: [
        // Mockup HTML is generated dynamically, so we don't scan source files.
        // Everything we want comes from the safelist below.
        { raw: '<div class="min-h-screen flex"></div>', extension: 'html' },
    ],
    theme: {
        extend: {
            keyframes: {
                shimmer: {
                    '100%': { transform: 'translateX(100%)' },
                },
            },
        },
    },
    plugins: [require('@tailwindcss/typography')],
    safelist: [
        // Color utilities (bg-*, text-*, border-*, etc.) across the full palette.
        // Only the bare utility is generated; hover/focus variants are added
        // selectively below for the properties that actually need them.
        {
            pattern: new RegExp(
                `^(${colorProperties.join('|')})-((${PALETTE})(-(${SHADES}))?|white|black|transparent|current|inherit)$`,
            ),
        },
        // Hover/focus variants for backgrounds & text only (the common case).
        {
            pattern: new RegExp(
                `^(bg|text|border|ring)-((${PALETTE})(-(${SHADES}))?|white|black|transparent|current)$`,
            ),
            variants: ['hover', 'focus', 'focus-visible', 'group-hover', 'disabled'],
        },

        // Spacing utilities (p-*, m-*, gap-*, space-*, inset-*, top-*, etc.)
        {
            pattern: new RegExp(
                `^(p|m|px|py|pt|pb|pl|pr|mx|my|mt|mb|ml|mr|gap|gap-x|gap-y|space-x|space-y|inset|top|right|bottom|left)-(${SPACING}|auto)$`,
            ),
            variants: RESPONSIVE,
        },
        // Negative spacing
        {
            pattern: new RegExp(
                `^-(m|mx|my|mt|mb|ml|mr|inset|top|right|bottom|left)-(${SPACING})$`,
            ),
        },

        // Sizing utilities (w-*, h-*, min-w-*, etc.)
        {
            pattern: new RegExp(
                `^(w|h|min-w|min-h|max-w|max-h|size)-(${SPACING}|${SIZE_KEYWORDS}|${FRACTIONS}|${MAX_W_NAMED})$`,
            ),
            variants: RESPONSIVE,
        },

        // Typography
        { pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl|9xl)$/, variants: RESPONSIVE },
        { pattern: /^font-(thin|extralight|light|normal|medium|semibold|bold|extrabold|black|sans|serif|mono)$/ },
        { pattern: /^leading-(none|tight|snug|normal|relaxed|loose|3|4|5|6|7|8|9|10)$/ },
        { pattern: /^tracking-(tighter|tight|normal|wide|wider|widest)$/ },
        { pattern: /^text-(left|center|right|justify|start|end)$/ },
        { pattern: /^(uppercase|lowercase|capitalize|normal-case|italic|not-italic|underline|line-through|no-underline|truncate|antialiased|subpixel-antialiased)$/ },
        { pattern: /^whitespace-(normal|nowrap|pre|pre-line|pre-wrap|break-spaces)$/ },
        { pattern: /^break-(normal|words|all|keep)$/ },
        { pattern: /^line-clamp-(none|1|2|3|4|5|6)$/ },
        { pattern: /^list-(none|disc|decimal|inside|outside)$/ },

        // Layout / display
        { pattern: /^(block|inline-block|inline|flex|inline-flex|grid|inline-grid|hidden|table|table-row|table-cell|contents|flow-root)$/, variants: RESPONSIVE },
        { pattern: /^(static|fixed|absolute|relative|sticky)$/ },
        { pattern: /^(visible|invisible|collapse)$/ },
        { pattern: /^z-(0|10|20|30|40|50|auto)$/ },
        { pattern: /^overflow-(auto|hidden|clip|visible|scroll|x-auto|x-hidden|x-clip|x-visible|x-scroll|y-auto|y-hidden|y-clip|y-visible|y-scroll)$/ },
        { pattern: /^overscroll-(auto|contain|none|x-auto|x-contain|x-none|y-auto|y-contain|y-none)$/ },

        // Flex / grid
        { pattern: /^flex-(row|row-reverse|col|col-reverse|wrap|wrap-reverse|nowrap|1|auto|initial|none)$/, variants: RESPONSIVE },
        { pattern: /^grow(-0)?$/ },
        { pattern: /^shrink(-0)?$/ },
        { pattern: /^basis-(auto|full|0|1|2|3|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96|1\/2|1\/3|2\/3|1\/4|2\/4|3\/4)$/ },
        { pattern: /^justify-(start|end|center|between|around|evenly|normal|stretch)$/, variants: RESPONSIVE },
        { pattern: /^items-(start|end|center|baseline|stretch)$/, variants: RESPONSIVE },
        { pattern: /^content-(start|end|center|between|around|evenly|baseline|stretch|normal)$/ },
        { pattern: /^self-(auto|start|end|center|stretch|baseline)$/ },
        { pattern: /^place-(content|items|self)-(start|end|center|between|around|evenly|stretch|baseline|auto)$/ },
        { pattern: /^order-(none|first|last|0|1|2|3|4|5|6|7|8|9|10|11|12)$/ },

        // Grid template
        { pattern: /^grid-cols-(none|subgrid|1|2|3|4|5|6|7|8|9|10|11|12)$/, variants: RESPONSIVE },
        { pattern: /^grid-rows-(none|subgrid|1|2|3|4|5|6)$/ },
        { pattern: /^col-(auto|span-(1|2|3|4|5|6|7|8|9|10|11|12|full)|start-(1|2|3|4|5|6|7|8|9|10|11|12|13|auto)|end-(1|2|3|4|5|6|7|8|9|10|11|12|13|auto))$/, variants: RESPONSIVE },
        { pattern: /^row-(auto|span-(1|2|3|4|5|6|full)|start-(1|2|3|4|5|6|7|auto)|end-(1|2|3|4|5|6|7|auto))$/ },

        // Borders & radius
        { pattern: /^rounded(-(none|sm|md|lg|xl|2xl|3xl|full))?$/ },
        { pattern: /^rounded-(t|r|b|l|tl|tr|bl|br|ss|se|es|ee)(-(none|sm|md|lg|xl|2xl|3xl|full))?$/ },
        { pattern: /^border(-(0|2|4|8))?$/ },
        { pattern: /^border-(t|r|b|l|x|y)(-(0|2|4|8))?$/ },
        { pattern: /^border-(solid|dashed|dotted|double|hidden|none)$/ },
        { pattern: /^divide-(x|y|x-reverse|y-reverse|solid|dashed|dotted|double|none)$/ },
        { pattern: /^divide-(x|y)-(0|2|4|8)$/ },
        { pattern: /^ring(-(0|1|2|4|8|inset))?$/, variants: ['hover', 'focus', 'focus-visible'] },
        { pattern: /^ring-offset-(0|1|2|4|8)$/ },
        { pattern: /^outline(-(none|0|1|2|4|8|dashed|dotted|double|offset-(0|1|2|4|8)))?$/ },

        // Effects
        { pattern: /^shadow(-(sm|md|lg|xl|2xl|inner|none))?$/, variants: ['hover', 'focus'] },
        { pattern: /^opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100)$/, variants: ['hover', 'group-hover'] },
        { pattern: /^blur(-(none|sm|md|lg|xl|2xl|3xl))?$/ },
        { pattern: /^backdrop-blur(-(none|sm|md|lg|xl|2xl|3xl))?$/ },
        { pattern: /^bg-(gradient-to-(t|tr|r|br|b|bl|l|tl)|none|cover|contain|center|top|right|bottom|left|repeat|no-repeat|repeat-x|repeat-y|fixed|local|scroll|clip-border|clip-padding|clip-content|clip-text)$/ },

        // Transitions & transforms
        { pattern: /^transition(-(none|all|colors|opacity|shadow|transform))?$/ },
        { pattern: /^duration-(0|75|100|150|200|300|500|700|1000)$/ },
        { pattern: /^ease-(linear|in|out|in-out)$/ },
        { pattern: /^animate-(none|spin|ping|pulse|bounce|shimmer)$/ },
        { pattern: /^(scale|rotate|translate-x|translate-y|skew-x|skew-y)-(0|1|2|3|6|12|45|50|75|90|95|100|105|110|125|150|180)$/ },
        { pattern: /^transform(-(gpu|none))?$/ },
        { pattern: /^origin-(center|top|top-right|right|bottom-right|bottom|bottom-left|left|top-left)$/ },

        // Interactivity
        { pattern: /^cursor-(auto|default|pointer|wait|text|move|help|not-allowed|none|grab|grabbing|copy)$/ },
        { pattern: /^pointer-events-(none|auto)$/ },
        { pattern: /^select-(none|text|all|auto)$/ },
        { pattern: /^resize(-(none|y|x))?$/ },
        { pattern: /^scroll-(auto|smooth)$/ },
        { pattern: /^appearance-(none|auto)$/ },

        // Tables
        { pattern: /^table-(auto|fixed|caption|cell|column|column-group|footer-group|header-group|row-group|row)$/ },
        { pattern: /^(border-collapse|border-separate)$/ },
        { pattern: /^border-spacing(-(0|1|2|4|8))?$/ },

        // Aspect ratio
        { pattern: /^aspect-(auto|square|video)$/ },

        // Object fit
        { pattern: /^object-(contain|cover|fill|none|scale-down|bottom|center|left|left-bottom|left-top|right|right-bottom|right-top|top)$/ },

        // Misc / explicit base shell classes
        'min-h-screen', 'min-h-full', 'h-screen', 'w-screen',
        'antialiased', 'font-sans', 'font-serif', 'font-mono',
        'sr-only', 'not-sr-only',
        'container',
    ],
};
