import type {
    ExportOptions,
    ExportResult,
    ImplementationTask,
    TaskExportProvider,
    TaskExportItemResult,
} from '../../../types/tasks';
import { getLocalCredential, GITHUB_TOKEN } from '../../localCredentials';

const GITHUB_REPO_KEY = 'GITHUB_DEFAULT_REPO';

interface GithubRepoCoords {
    owner: string;
    repo: string;
}

function readToken(): string | null {
    if (typeof localStorage === 'undefined') return null;
    const raw = getLocalCredential(GITHUB_TOKEN)?.trim();
    return raw ? raw : null;
}

function readDefaultRepo(): GithubRepoCoords | null {
    if (typeof localStorage === 'undefined') return null;
    const raw = localStorage.getItem(GITHUB_REPO_KEY)?.trim();
    return parseRepo(raw);
}

export function parseRepo(value: string | undefined | null): GithubRepoCoords | null {
    if (!value) return null;
    const cleaned = value.trim().replace(/^https?:\/\/github\.com\//i, '').replace(/\.git$/, '');
    const match = cleaned.match(/^([^\s/]+)\/([^\s/]+)$/);
    if (!match) return null;
    return { owner: match[1], repo: match[2] };
}

export function buildGithubIssueBody(task: ImplementationTask, projectName?: string): string {
    const lines: string[] = [];
    lines.push('## Summary');
    lines.push(task.summary || task.title);
    lines.push('');
    lines.push('## Source');
    const sourceParts: string[] = ['Implementation Plan'];
    if (projectName) sourceParts.push(projectName);
    if (task.sourceSectionId) sourceParts.push(task.sourceSectionId);
    lines.push(sourceParts.join(' · '));
    lines.push('');
    lines.push('## Acceptance Criteria');
    if (task.acceptanceCriteria.length === 0) {
        lines.push('- [ ] (no criteria captured — please define before starting)');
    } else {
        for (const criterion of task.acceptanceCriteria) {
            lines.push(`- [ ] ${criterion}`);
        }
    }
    lines.push('');
    if (task.implementationNotes && task.implementationNotes.length) {
        lines.push('## Implementation Notes');
        for (const note of task.implementationNotes) {
            lines.push(`- ${note}`);
        }
        lines.push('');
    }
    if (task.dependencies && task.dependencies.length) {
        lines.push('## Dependencies');
        for (const dep of task.dependencies) {
            lines.push(`- ${dep}`);
        }
        lines.push('');
    }
    if (task.priority || task.estimatedComplexity || task.taskType) {
        const meta: string[] = [];
        if (task.taskType) meta.push(`**Type:** ${task.taskType}`);
        if (task.priority) meta.push(`**Priority:** ${task.priority}`);
        if (task.estimatedComplexity) meta.push(`**Complexity:** ${task.estimatedComplexity}`);
        lines.push(meta.join('  '));
        lines.push('');
    }
    lines.push('---');
    lines.push('_Generated by Synapse._');
    return lines.join('\n');
}

export interface GithubIssuePayload {
    title: string;
    body: string;
    labels: string[];
}

export function buildGithubIssuePayload(
    task: ImplementationTask,
    projectName?: string,
): GithubIssuePayload {
    return {
        title: task.title,
        body: buildGithubIssueBody(task, projectName),
        labels: [...(task.suggestedLabels ?? [])],
    };
}

interface GithubLabelDescriptor {
    name: string;
}

async function fetchExistingLabels(
    coords: GithubRepoCoords,
    token: string,
    fetchImpl: typeof fetch,
): Promise<Set<string> | null> {
    try {
        const url = `https://api.github.com/repos/${coords.owner}/${coords.repo}/labels?per_page=100`;
        const response = await fetchImpl(url, {
            headers: {
                Authorization: `Bearer ${token}`,
                Accept: 'application/vnd.github+json',
                'X-GitHub-Api-Version': '2022-11-28',
            },
        });
        if (!response.ok) {
            // Non-fatal: caller will simply skip the warning system.
            return null;
        }
        const json = (await response.json()) as GithubLabelDescriptor[];
        return new Set(json.map(l => l.name));
    } catch {
        return null;
    }
}

export interface GithubExportDeps {
    fetchImpl?: typeof fetch;
    /** Override for tests. Defaults to localStorage lookup. */
    token?: string;
    /** Override for tests. Defaults to localStorage lookup. */
    repo?: GithubRepoCoords;
}

export async function exportTasksToGithub(
    tasks: ImplementationTask[],
    options: ExportOptions,
    deps: GithubExportDeps = {},
): Promise<ExportResult> {
    const fetchImpl = deps.fetchImpl ?? globalThis.fetch;
    const token = deps.token ?? readToken();
    const coords = deps.repo ?? readDefaultRepo();

    if (!token) {
        return {
            target: 'github',
            succeeded: [],
            failed: [],
            fatalError: 'No GitHub token found. Add one in Settings → Integrations.',
        };
    }
    if (!coords) {
        return {
            target: 'github',
            succeeded: [],
            failed: [],
            fatalError: 'No GitHub repo configured. Add `owner/repo` in Settings → Integrations.',
        };
    }
    if (typeof fetchImpl !== 'function') {
        return {
            target: 'github',
            succeeded: [],
            failed: [],
            fatalError: 'No fetch implementation available in this environment.',
        };
    }

    const existingLabels = await fetchExistingLabels(coords, token, fetchImpl);

    const succeeded: TaskExportItemResult[] = [];
    const failed: TaskExportItemResult[] = [];

    for (const task of tasks) {
        const payload = buildGithubIssuePayload(task, options.projectName);
        let labels = payload.labels;
        const warnings: string[] = [];
        if (existingLabels) {
            const filtered = labels.filter(l => existingLabels.has(l));
            const missing = labels.filter(l => !existingLabels.has(l));
            if (missing.length) {
                warnings.push(
                    `Skipped labels not present on ${coords.owner}/${coords.repo}: ${missing.join(', ')}`,
                );
            }
            labels = filtered;
        }

        try {
            const url = `https://api.github.com/repos/${coords.owner}/${coords.repo}/issues`;
            const response = await fetchImpl(url, {
                method: 'POST',
                headers: {
                    Authorization: `Bearer ${token}`,
                    Accept: 'application/vnd.github+json',
                    'X-GitHub-Api-Version': '2022-11-28',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ ...payload, labels }),
            });
            if (!response.ok) {
                const body = await safeReadBody(response);
                failed.push({
                    taskId: task.id,
                    title: task.title,
                    error: `GitHub returned ${response.status}: ${body}`,
                    warnings: warnings.length ? warnings : undefined,
                });
                continue;
            }
            const json = (await response.json()) as { html_url?: string; number?: number };
            succeeded.push({
                taskId: task.id,
                title: task.title,
                externalUrl: json.html_url,
                externalId: typeof json.number === 'number' ? `#${json.number}` : undefined,
                warnings: warnings.length ? warnings : undefined,
            });
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : String(err);
            failed.push({
                taskId: task.id,
                title: task.title,
                error: message,
                warnings: warnings.length ? warnings : undefined,
            });
        }
    }

    return {
        target: 'github',
        succeeded,
        failed,
    };
}

async function safeReadBody(response: Response): Promise<string> {
    try {
        const text = await response.text();
        return text.slice(0, 500);
    } catch {
        return '(could not read response body)';
    }
}

export const githubExporter: TaskExportProvider = {
    id: 'github',
    label: 'GitHub Issues',
    checkReady() {
        if (!readToken()) return 'Add a GitHub token in Settings → Integrations.';
        if (!readDefaultRepo()) return 'Add a default `owner/repo` in Settings → Integrations.';
        return null;
    },
    exportTasks: (tasks, options) => exportTasksToGithub(tasks, options),
};
