import type {
    ExportOptions,
    ExportResult,
    ImplementationTask,
    TaskExportProvider,
} from '../../../types/tasks';
import { downloadFile } from '../../utils/downloadFile';

/**
 * Render a single `ImplementationTask` as a markdown section. Exposed
 * separately so unit tests (and the in-app preview, if we ever want it)
 * can render a task without triggering a download.
 */
export function renderTaskMarkdown(task: ImplementationTask, index: number): string {
    const lines: string[] = [];
    lines.push(`## ${index + 1}. ${task.title}`);
    lines.push('');
    const meta: string[] = [];
    if (task.taskType) meta.push(`**Type:** ${capitalize(task.taskType)}`);
    if (task.priority) meta.push(`**Priority:** ${capitalize(task.priority)}`);
    if (task.estimatedComplexity) meta.push(`**Complexity:** ${capitalize(task.estimatedComplexity)}`);
    if (meta.length) {
        lines.push(meta.join('  '));
        lines.push('');
    }
    if (task.summary) {
        lines.push('### Summary');
        lines.push(task.summary);
        lines.push('');
    }
    lines.push('### Acceptance Criteria');
    if (task.acceptanceCriteria.length === 0) {
        lines.push('- [ ] (no criteria captured — please define before starting)');
    } else {
        for (const criterion of task.acceptanceCriteria) {
            lines.push(`- [ ] ${criterion}`);
        }
    }
    lines.push('');
    if (task.implementationNotes && task.implementationNotes.length) {
        lines.push('### Implementation Notes');
        for (const note of task.implementationNotes) {
            lines.push(`- ${note}`);
        }
        lines.push('');
    }
    if (task.dependencies && task.dependencies.length) {
        lines.push('### Dependencies');
        for (const dep of task.dependencies) {
            lines.push(`- ${dep}`);
        }
        lines.push('');
    }
    if (task.suggestedLabels && task.suggestedLabels.length) {
        lines.push(`**Labels:** ${task.suggestedLabels.join(', ')}`);
        lines.push('');
    }
    if (task.sourceSectionId) {
        lines.push(`_Source: Implementation Plan → ${task.sourceSectionId}_`);
        lines.push('');
    }
    return lines.join('\n');
}

export function renderTasksMarkdown(
    tasks: ImplementationTask[],
    projectName: string | undefined,
): string {
    const header = `# Implementation Tasks${projectName ? ` — ${projectName}` : ''}`;
    const intro = `_Generated by Synapse from an Implementation Plan artifact. ${tasks.length} task${tasks.length === 1 ? '' : 's'}._`;
    const body = tasks.map((task, i) => renderTaskMarkdown(task, i)).join('\n');
    return `${header}\n\n${intro}\n\n${body}`.trim() + '\n';
}

function capitalize(s: string): string {
    return s.length ? s.charAt(0).toUpperCase() + s.slice(1) : s;
}

function safeFilename(projectName: string | undefined): string {
    const base = (projectName || 'synapse').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    return `${base || 'synapse'}-tasks.md`;
}

export const markdownExporter: TaskExportProvider = {
    id: 'markdown',
    label: 'Markdown',
    checkReady() {
        return null;
    },
    async exportTasks(tasks: ImplementationTask[], options: ExportOptions): Promise<ExportResult> {
        const content = renderTasksMarkdown(tasks, options.projectName);
        const filename = safeFilename(options.projectName);
        // Tests run in jsdom; URL.createObjectURL is mocked at the global
        // level when needed. In environments where it isn't, the download
        // call throws — caught here and surfaced as a fatal error.
        try {
            downloadFile(content, filename);
        } catch (err: unknown) {
            const message = err instanceof Error ? err.message : String(err);
            return {
                target: 'markdown',
                succeeded: [],
                failed: tasks.map(t => ({ taskId: t.id, title: t.title, error: message })),
                fatalError: `Could not save the markdown file: ${message}`,
            };
        }
        return {
            target: 'markdown',
            succeeded: tasks.map(t => ({ taskId: t.id, title: t.title })),
            failed: [],
            notes: [`Saved ${tasks.length} task${tasks.length === 1 ? '' : 's'} to ${filename}.`],
        };
    },
};
